// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicationInventoryManagement.Entities;

public partial class Medication
{
    [Key]
    public Guid MedicationId { get; set; }

    [Required]
    [StringLength(50)]
    public string MedicationName { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ExpirationDate { get; set; }

    [InverseProperty("Medication")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [ForeignKey("MedicationId")]
    [InverseProperty("Medications")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}