// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicationInventoryManagement.Entities;

[Table("OrderMedication")]
public partial class OrderMedication
{
    [Key]
    public Guid OrderMedicationId { get; set; }

    public Guid MedicationId { get; set; }

    public Guid OrderId { get; set; }

    [Column("newQuantity")]
    public int NewQuantity { get; set; }

    [ForeignKey("MedicationId")]
    [InverseProperty("OrderMedications")]
    public virtual Medication Medication { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderMedications")]
    public virtual Order Order { get; set; }
}