// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicationInventoryManagement.Entities;

public partial class User
{
    [Key]
    [Column("userId")]
    public Guid UserId { get; set; }

    [Required]
    [StringLength(20)]
    public string UserName { get; set; }

    [Required]
    [Column("password")]
    public string Password { get; set; }
}